services:
  app:
    build: .
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    links:
      - postgres
    depends_on:
      - postgres
    ports: 
      - "4000:4000"
    volumes:
      - .:/code
    container_name: hw3

  postgres:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - .postgres-data:/var/lib/postgresql/data
    container_name: flask_postgres
